services:
  - type: web
    name: nephropredict-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r server/fastapi/production_requirements.txt
      chmod +x render_start.sh
      cp -f server/fastapi/render_main.py server/fastapi/main.py
    startCommand: ./render_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 1
      - key: TIMEOUT
        value: 120
    healthCheckPath: /health
